spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.32.11:3306/im
    username: root
    password: root111111
  data:
    redis:
      host: 124.223.32.11
      port: 6379
      password: 'redis111111'
      lettuce:
        pool:
          max-active: 100
          max-idle: 100
          min-idle: 10
          max-wait: 1000
  rabbitmq:
    host: 124.223.32.11
    port: 5672
    addresses: 124.223.32.11
    userName: pius
    password: 123456
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0
    publisher-returns: true
    publisher-confirm-type: correlated

appConfig:
  zkAddr: 124.223.32.11:2181 # zk连接地址
  zkConnectTimeOut: 10000 #zk超时时间
  imRouteStrategy: 3 # 路由策略 1.随机 2.轮询 3.一致性hash
  consistentHashImpl: 1 # 一致性hash的具体实现 1.TreeMap 2.自定义Map
  callbackUrl: http://127.0.0.1:8989/callback
  modifyUserAfterCallback: false # 用户资料变更之后回调开关
  addFriendAfterCallback: false # 添加好友之后回调开关
  addFriendBeforeCallback: false # 添加好友之前回调开关
  modifyFriendAfterCallback: false # 修改好友之后回调开关
  deleteFriendAfterCallback: false # 删除好友之后回调开关
  addFriendShipBlackAfterCallback: false #添加黑名单之后回调开关
  deleteFriendShipBlackAfterCallback: false #删除黑名单之后回调开关
  createGroupAfterCallback: false # 创建群聊之后回调开关
  modifyGroupAfterCallback: false # 修改群聊之后回调开关
  destroyGroupAfterCallback: false # 解散群聊之后回调开关
  deleteGroupMemberAfterCallback: false # 删除群成员之后回调
  addGroupMemberAfterCallback: false # 拉人入群之后回调
  addGroupMemberBeforeCallback: false # 拉人入群之前回调

# logger 配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true