spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.32.11:3306/im
    username: root
    password: root111111
  data:
    redis:
      host: 124.223.32.11
      port: 6379
      password: 'redis111111'
      lettuce:
        pool:
          max-active: 100
          max-idle: 100
          min-idle: 10
          max-wait: 1000
  rabbitmq:
    host: 124.223.32.11
    port: 5672
    addresses: 124.223.32.11
    userName: pius
    password: 123456
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0
    publisher-returns: true
    publisher-confirm-type: correlated

# logger 配置
logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY